# Curso de Inteligencia Artificial

### <font color='green'> Alumno:________________</font>
### <font color='blue'> Mtro. Alejandro I. Trejo-Castro</font>

### 2.2 Matrices

Recuerda que este curso tiene 9 capítulos que son los siguientes:
- `1. Introducción a IA`
- `2. Matemáticas para la ciencia de datos`
- `3. Análisis Exploratorio de Datos`
- `4. Probabilidad y Estadística`
- `5. Aprendizaje supervisado`
- `6. Aprendizaje no supervisado`
- `7. Minería de textos`
- `8. Redes neuronales y Deep Learning`
- `9. Temas avanzados de Deep Learning`
  
<font color='purple'> ¡Divirtámonos!</font>

##### <font color='red'>Unidad 3 Comprender la ciencia de datos: Matriz </font>

#### 3.1 Cálculo de Matrices

###### Importar la Biblioteca Necesaria

In [1]:
import numpy as np

##### Matriz

In [2]:
# Crear una matriz 2x3
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz 2x3:")
print(matriz)

Matriz 2x3:
[[1 2 3]
 [4 5 6]]


In [3]:
matriz.shape

(2, 3)

##### Calcular el número de filas y columnas de una matriz

In [4]:
# Calcular el número de filas y columnas
num_filas = matriz.shape[0]
num_columnas = matriz.shape[1]

# Mostrar los resultados
print("Número de filas:", num_filas)
print("Número de columnas:", num_columnas)
print("Dimensiones", matriz.shape)

Número de filas: 2
Número de columnas: 3
Dimensiones (2, 3)


##### Matriz Transposición

In [5]:
# Transponer una matriz
matriz_transpuesta = matriz.T
print("\nMatriz Transpuesta:")
print(matriz_transpuesta)


Matriz Transpuesta:
[[1 4]
 [2 5]
 [3 6]]


In [6]:
matriz_transpuesta = np.transpose(matriz)
print("\nMatriz Transpuesta:")
print(matriz_transpuesta)


Matriz Transpuesta:
[[1 4]
 [2 5]
 [3 6]]


In [7]:
matriz_transpuesta = matriz.transpose()
print("\nMatriz Transpuesta:")
print(matriz_transpuesta)


Matriz Transpuesta:
[[1 4]
 [2 5]
 [3 6]]


##### Expresión Matricial de Polinomios

In [8]:
A = np.array([[1, 2], 
              [3, 4]])

polinomio = np.dot(A, A)
print(polinomio)

[[ 7 10]
 [15 22]]


In [9]:
# Expresar un polinomio matricial (ejemplo: A^2 + 2A + I)
A = np.array([[1, 2], 
              [3, 4]])
I = np.eye(2)
polinomio = np.dot(A, A) + 2*A + I
print("\nPolinomio Matricial (A^2 + 2A + I):")
print(polinomio)


Polinomio Matricial (A^2 + 2A + I):
[[10. 14.]
 [21. 31.]]


In [10]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##### Matriz cuadrada

In [11]:
# Crear una matriz cuadrada 3x3
matriz_cuadrada = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz Cuadrada 3x3:\n")
print(matriz_cuadrada)

Matriz Cuadrada 3x3:

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Matriz Diagonal

In [12]:
# Crear una matriz diagonal
matriz_diagonal = np.diag([1, 2, 3, 4])
print("\nMatriz Diagonal:")
print(matriz_diagonal)


Matriz Diagonal:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


##### Matriz Identidad (unitaria)

In [13]:
# Crear una matriz identidad (unitaria)
matriz_identidad = np.eye(10)
print("\nMatriz Identidad:")
print(matriz_identidad)


Matriz Identidad:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


##### Matriz Simétrica

In [14]:
# Crear una matriz aleatoria
np.random.seed(0)
A = np.random.randint(1, 20, size=(5, 5))
print("Matriz original:")
print(A)

# Hacer la matriz simétrica
matriz_simetrica = (A + A.T) / 2
print("\nMatriz Simétrica:")
print(matriz_simetrica)

Matriz original:
[[13 16  1  4  4]
 [ 8 10 19  5  7]
 [13  2  7  8 15]
 [18  6 14  9 10]
 [17  6 16 16  1]]

Matriz Simétrica:
[[13.  12.   7.  11.  10.5]
 [12.  10.  10.5  5.5  6.5]
 [ 7.  10.5  7.  11.  15.5]
 [11.   5.5 11.   9.  13. ]
 [10.5  6.5 15.5 13.   1. ]]


##### Multiplicación de Matrices

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
multiplicacion = np.dot(A, B)
print("\nMultiplicación de Matrices:")
print(multiplicacion)


Multiplicación de Matrices:
[[22 28]
 [49 64]]


In [16]:
A = np.array([[1, 2], [4, 5]])
B = np.array([[1, 2], [3, 4], [5, 6]])
multiplicacion = np.dot(B, A)
print("\nMultiplicación de Matrices:")
print(multiplicacion)


Multiplicación de Matrices:
[[ 9 12]
 [19 26]
 [29 40]]


In [17]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1], [3], [5]])
multiplicacion = np.dot(A, B)
print("\nMultiplicación de Matrices:")
print(multiplicacion)


Multiplicación de Matrices:
[[22]
 [49]]


##### Suma de Matrices

In [18]:
# Suma de matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 0, 1], [3, 5, 6]])
suma = A + B
print("\nSuma de Matrices:")
print(suma)


Suma de Matrices:
[[ 3  2  4]
 [ 7 10 12]]


In [19]:
np.add(A,B)

array([[ 3,  2,  4],
       [ 7, 10, 12]])

In [20]:
np.sum(A)

21

##### Resta de Matrices

In [21]:
# Resta de matrices
A = np.array([[5, 2, 8], [4, 10, 6]])
B = np.array([[2, 0, 1], [7, 5, 0]])
resta = A - B
print("\nResta de Matrices:")
print(resta)
print('---------------')
print(B-A)


Resta de Matrices:
[[ 3  2  7]
 [-3  5  6]]
---------------
[[-3 -2 -7]
 [ 3 -5 -6]]


##### Multiplicación Escalar de Matrices

In [22]:
# Multiplicación escalar
escalar = 2
B = np.array([[2, 0, 1], [7, 5, 0]])
multiplicacion_escalar = escalar * B
print("\nMultiplicación Escalar:")
print(multiplicacion_escalar)


Multiplicación Escalar:
[[ 4  0  2]
 [14 10  0]]


##### Producto Elemento a Elemento

In [23]:
# Inicializa el vector 'x'
x = np.array([[2],[3],[1]])

# Inicializa el vector 'y'
y = np.array([[1],[5],[2]])

# Calcula el producto elemento a elemento
prod = np.multiply(x, y)

# Imprime el resultado
print(f"El producto elemento a elemento entre el vector x y y es: \n {prod}")

El producto elemento a elemento entre el vector x y y es: 
 [[ 2]
 [15]
 [ 2]]


In [24]:
x * y

array([[ 2],
       [15],
       [ 2]])

#### 3.2 Matriz Inversa

##### Matriz Inversa

In [25]:
# Matriz inversa (solo para matrices cuadradas e invertibles)
matriz_invertible = np.array([[1, 2], [3, 4]])
try:
    matriz_inversa = np.linalg.inv(matriz_invertible)
    print("\nMatriz Inversa:")
    print(matriz_inversa)
except np.linalg.LinAlgError:
    print("\nLa matriz no es invertible.")


Matriz Inversa:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
np.dot(matriz_invertible, matriz_inversa)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

##### Determinante

In [27]:
matriz_cuadrada = np.array([[1,4],[5,6]])
matriz_cuadrada

array([[1, 4],
       [5, 6]])

In [28]:
# Determinante de una matriz cuadrada
determinante = np.linalg.det(matriz_cuadrada)
print("\nDeterminante de la Matriz Cuadrada:")
print(determinante)


Determinante de la Matriz Cuadrada:
-13.999999999999996


In [29]:
print(f"Determinante: {determinante:.2f}")

Determinante: -14.00


##### Matriz que no es invertible

In [30]:
# Crear una matriz cuadrada
A = np.array([[1, 2], [2, 4]])

# Calcular el determinante de la matriz
determinante = np.linalg.det(A)
print("Determinante de la matriz:")
print(determinante)

# Verificar si la matriz es invertible
if determinante == 0:
    print("\nLa matriz no es invertible (singular).")
else:
    print("\nLa matriz es invertible.")

Determinante de la matriz:
0.0

La matriz no es invertible (singular).


##### Ejemplos de la vida real

In [31]:
# Analizar una red social simple con matrices de adyacencia
# Representación de la red (Matriz de Adyacencia)
red = np.array([
    [0, 1, 1, 0],  # Nodo 1
    [1, 0, 1, 1],  # Nodo 2
    [1, 1, 0, 1],  # Nodo 3
    [0, 1, 1, 0]   # Nodo 4
])

print("\nMatriz de Adyacencia de la Red Social:")
print(red)

# Determinar el grado de cada nodo (suma de filas)
grados = np.sum(red, axis=1)
print("\nGrado de cada Nodo:")
print(grados)


Matriz de Adyacencia de la Red Social:
[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 1]
 [0 1 1 0]]

Grado de cada Nodo:
[2 3 3 2]


In [32]:
# Precio constante del acero por tonelada durante enero, febrero, marzo
c = np.array([[2145], [2530], [2314]])

# Producción de toneladas de acero durante enero, febrero, marzo
p = np.array([[2], [3], [1]])

# Obtiene el ingreso mensual 'y'
y = np.multiply(c, p)

# Imprime el ingreso mensual'y'
print(f'El ingreso por mes es: \n {y}')

El ingreso por mes es: 
 [[4290]
 [7590]
 [2314]]


In [33]:
# Costo por tonelada de acero para los diferentes meses
c = np.array([[2145],[2530],[2314],[2615],[2618],[2597],[2578],[2515],[2531],[2538],[2541],[2500]])

print(c)

[[2145]
 [2530]
 [2314]
 [2615]
 [2618]
 [2597]
 [2578]
 [2515]
 [2531]
 [2538]
 [2541]
 [2500]]


In [34]:
# Costo por tonelada de acero para los diferentes meses
c = np.array([[2145],[2530],[2314],[2615],[2618],[2597],[2578],[2515],[2531],[2538],[2541],[2500]])

# Producción de toneladas de acero en Australia, Francia, y Argentina
P = np.array([[38.67, 39.58, 39.10],
              [41.98, 40.75, 41.01],
              [44.21, 45.37, 45.27],
              [45.25, 46.52, 46.55],
              [50.85, 51.58, 51.88],
              [45.78, 44.87, 45.77],
              [42.72, 41.27, 42.22],
              [42.51, 44.15, 43.11],
              [41.02, 41.20, 41.89],
              [41.07, 42.70, 43.07],
              [35.86, 35.68, 35.99],
              [36.19, 37.10, 37.87]])

# Obtiene el ingreso anual para cada sede
y = np.matmul(P.T, c)
y2 = np.dot(P.transpose(), c)
# Imprime el ingreso anual 'y'
print(f"El ingreso anual es: \n {y}")
print('.............')
print(y2)

El ingreso anual es: 
 [[1268500.55]
 [1279690.4 ]
 [1287520.01]]
.............
[[1268500.55]
 [1279690.4 ]
 [1287520.01]]
