# Curso de Inteligencia Artificial

### <font color='green'> Alumno: ______________________</font>
### <font color='blue'> Profesor: Alejandro I. Trejo-Castro</font>

### 3.1. Análisis Exploratorio con NumPy.

*Bienvenidos* a este jupyter notebook que nos será de utilidad para comprender las operaciones básicas y códigos introductorios en Python.

**Recuerda que este curso cubre los siguientes capítulos:**
- `0. Entorno de trabajo`
- `1. Introducción a la Inteligencia Artificial`
- `2. Matemáticas básicas para Ciencia de Datos`
- `3. Análisis Exploratorio de Datos`
- `4. Probabilidad y Estadística`
- `5. Aprendizaje Supervisado`
- `6. Aprendizaje No Supervisado`
- `7. Procesamiento de Lenguaje Natural y Minería de Texto`
- `8. Redes Neuronales y Aprendizaje Profundo`
- `9. Otros tipos de Redes Neuronales`
- `10. IA Generativa`

<font color='purple'> ¡Divirtámonos!</font>

### 1. Crear un arreglo

#### Crea un arreglo de números del 0 al 10 e imprime su tipo de datos y su dimensión.

In [1]:
import numpy as np
x = np.arange(11)
a = np.array(x)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape

(11,)

In [4]:
a.ndim

1

In [5]:
b = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
print(type(b))
b.shape

<class 'numpy.ndarray'>


(11,)

#### Convierte el arreglo en un arreglo de tipo float y vuelve a imprimirlo

In [7]:
a = a.astype(float)
print(type(a))
a

<class 'numpy.ndarray'>


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 2. Operaciones básicas

#### Genera dos arreglos aleatorios de 5 elementos cada uno.

In [8]:
np.random.rand()

0.4493140103218516

In [9]:
import random
np.random.seed(42)

v1 = np.random.randint(0, 10, 5)
v2 = np.random.randint(0, 10, 5)
print("Versión 1:",v1)
print("Versión 2:",v2)

Versión 1: [6 3 7 4 6]
Versión 2: [9 2 6 7 4]


#### Realiza las siguientes operaciones entre ambos arreglos: suma, resta, multiplicación y división elemento a elemento.

In [10]:
print("Suma", v1+v2)
print("Resta",v1-v2)
print("Multiplicacion", v1*v2)
print("Division", v1/v2)

Suma [15  5 13 11 10]
Resta [-3  1  1 -3  2]
Multiplicacion [54  6 42 28 24]
Division [0.66666667 1.5        1.16666667 0.57142857 1.5       ]


#### Calcula el promedio, la mediana y la desviación estándar de uno de los arreglos.

In [11]:
print("Promedio",np.mean(v1))
print("Mediana",np.median(v1))
print("Desviacion Estandar",np.std(v1))

print("Desviacion Estandar_muestra",np.round(np.std(v1, ddof=1),2))

Promedio 5.2
Mediana 6.0
Desviacion Estandar 1.469693845669907
Desviacion Estandar_muestra 1.64


In [12]:
import pandas as pd
v1 = pd.Series(v1)
print(v1)
v1.describe()

0    6
1    3
2    7
3    4
4    6
dtype: int32


count    5.000000
mean     5.200000
std      1.643168
min      3.000000
25%      4.000000
50%      6.000000
75%      6.000000
max      7.000000
dtype: float64

### 3. Índices y selección

#### Crea un arreglo de números del 1 al 25 y redimensionalo en una matriz de 5x5

In [13]:
matrix = np.array(np.arange(1,26))
matrix =  matrix.reshape((5, 5))

matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Selecciona:
##### a) La primera fila
##### b) La última columna
##### c) La submatriz de 3x3 en el centro de la matriz

In [14]:
matrix[0,:]

array([1, 2, 3, 4, 5])

In [15]:
matrix[:,-1]

array([ 5, 10, 15, 20, 25])

In [16]:
matrix[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [17]:
matrix[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

### 4. Uso de argmax y argmin

#### Genera un arreglo aleatorio de 10 elementos

In [18]:
np.random.seed(0)
arreglo = np.array(np.random.rand(10))

arreglo

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

#### Encuentra el índice del valor máximo y el índice del valor mínimo

In [19]:
ind = np.argmax(arreglo)
arreglo = pd.Series(arreglo)
valor = arreglo.iloc[ind]
print("Indice mayor", ind)
print("Valor",valor)

Indice mayor 8
Valor 0.9636627605010293


In [20]:
ind = np.argmin(arreglo)
arreglo = pd.Series(arreglo)
valor = arreglo.iloc[ind]
valor
print("Indice minimo", ind)
print("Valor",valor)

Indice minimo 9
Valor 0.3834415188257777


#### Cambia el valor máximo a 0 utilizando su índice

In [21]:
arreglo[8] = 0
print(arreglo)

0    0.548814
1    0.715189
2    0.602763
3    0.544883
4    0.423655
5    0.645894
6    0.437587
7    0.891773
8    0.000000
9    0.383442
dtype: float64


### 5. Filtrado y máscaras

#### Genera un arreglo de 20 elementos con valores entre -10 y 10

In [22]:
arreglo = np.array(np.random.randint(-10,11,20))
print(arreglo)
print(arreglo.shape)

[ -4  -3   4   7  -5   3  -2  -1  10   9   6   9  -5   5   5 -10   8  -7
   7   9]
(20,)


#### Crea una máscara para seleccionar solo los valores positivos y otro para los valores negativos.

#### Imprime ambos subconjuntos de valores

In [23]:
positivos = arreglo>0
arreglo[positivos==True]

array([ 4,  7,  3, 10,  9,  6,  9,  5,  5,  8,  7,  9])

In [24]:
negativos = arreglo<0
arreglo[negativos==True]

array([ -4,  -3,  -5,  -2,  -1,  -5, -10,  -7])

### 6. Funciones universales

#### Crea un arreglo de números del 1 al 10

In [25]:
arreglo = np.array(np.random.randint(1,11,30))
arreglo

array([ 4,  4,  8,  1,  2, 10, 10,  1,  5,  8,  4,  3,  8,  3,  1,  1,  5,
        6,  6,  7,  9,  5,  2,  5, 10,  9,  2,  2,  8, 10])

#### Calcula la raíz cuadrada, el seno y el logaritmo de cada elemento

#### Redondea cada valor del arreglo resultante a 2 decimales

In [26]:
np.round(np.sqrt(arreglo),2)

array([2.  , 2.  , 2.83, 1.  , 1.41, 3.16, 3.16, 1.  , 2.24, 2.83, 2.  ,
       1.73, 2.83, 1.73, 1.  , 1.  , 2.24, 2.45, 2.45, 2.65, 3.  , 2.24,
       1.41, 2.24, 3.16, 3.  , 1.41, 1.41, 2.83, 3.16])

In [27]:
np.round(np.sin(arreglo),2)

array([-0.76, -0.76,  0.99,  0.84,  0.91, -0.54, -0.54,  0.84, -0.96,
        0.99, -0.76,  0.14,  0.99,  0.14,  0.84,  0.84, -0.96, -0.28,
       -0.28,  0.66,  0.41, -0.96,  0.91, -0.96, -0.54,  0.41,  0.91,
        0.91,  0.99, -0.54])

In [28]:
np.round(np.log(arreglo),2)

array([1.39, 1.39, 2.08, 0.  , 0.69, 2.3 , 2.3 , 0.  , 1.61, 2.08, 1.39,
       1.1 , 2.08, 1.1 , 0.  , 0.  , 1.61, 1.79, 1.79, 1.95, 2.2 , 1.61,
       0.69, 1.61, 2.3 , 2.2 , 0.69, 0.69, 2.08, 2.3 ])

#### 7. Operaciones con matrices

#### Crea dos matrices de 3x3 con valores aleatorios

In [29]:
A = np.array(np.random.randint(0,10,9))
A = A.reshape((3,3))
print(A)

[[9 3 6]
 [7 2 0]
 [3 5 9]]


#### Realiza las siguientes operaciones entre ambas matrices:
#### a) Suma
#### b) Multiplicación elemento a elemento
#### c) Producto matricial (dot product)

In [30]:
B = np.array(np.random.randint(0,10,9))
B = B.reshape((3,3))
print(B)

[[4 4 6]
 [4 4 3]
 [4 4 8]]


In [31]:
A+B

array([[13,  7, 12],
       [11,  6,  3],
       [ 7,  9, 17]])

In [32]:
np.multiply(A,B)

array([[36, 12, 36],
       [28,  8,  0],
       [12, 20, 72]])

In [33]:
np.dot(A,B)

array([[ 72,  72, 111],
       [ 36,  36,  48],
       [ 68,  68, 105]])

#### Calcula la transpuesta y la inversa (si existe) de una de las amtrices

In [34]:
A.T

array([[9, 7, 3],
       [3, 2, 5],
       [6, 0, 9]])

In [35]:
np.linalg.det(A)

146.99999999999997

In [36]:
np.linalg.inv(A)

array([[ 0.12244898,  0.02040816, -0.08163265],
       [-0.42857143,  0.42857143,  0.28571429],
       [ 0.19727891, -0.24489796, -0.02040816]])

### 8. Estadísticas

#### Genera un arreglo de 100 elementos con números aleatorios entre 1 y 100

In [37]:
arreglo = np.array(np.random.randint(1,101,100))
arreglo

array([ 79,  16,  21, 100,  59,  24,  80,  14,  86,  49,  50,  70,  42,
        36,  65,  96,  70,  95,   1,  51,  37,  35,  49,  94,   4,  99,
        43,  78,  22,  74,   1,  11,  44,  59,  24,  60,   3,  99,  63,
        36,  95,  68,  83,  47, 100,  21,  82,  51,  28,  15,  42,  59,
        66,  37,  11,  87,  44,  12,   3,  52,  81,  33,  55,   1,  39,
        20,  47,  43,  57,  61,  78,  31,  25,   3,   4,  95,  99,  14,
        41,  73,  20,  96,  73,  27,  67,  53,  68,  62,  15,  97,   5,
        68,  12,  87,  78,  76,  57,  17,  25,  30])

#### Calcula la media, la mediana, el valor máximo, el valor mínimo y la desviación estándar

#### Encuentra el percentil 25, 50 y 75 de los datos

In [38]:
arreglo = pd.Series(arreglo)
arreglo.describe()

count    100.000000
mean      49.750000
std       29.699973
min        1.000000
25%       24.000000
50%       49.500000
75%       73.250000
max      100.000000
dtype: float64

In [39]:
np.random.seed(8)
stat_array = np.random.randint(1,101,100)

#Calculo de medias, medianas, max...
media = np.mean(stat_array)
mediana = np.median(stat_array)
max = np.max(stat_array)
min = np.min(stat_array)
desviacion_est = np.std(stat_array)
desviacion_est_m = np.std(stat_array,ddof=1)
#Calculo de percentiles
percentil25 = np.percentile(stat_array,25)
percentil50 = np.percentile(stat_array,50)
percentil75 = np.percentile(stat_array,75)
print("Arreglo:", stat_array)
print("Media:", media)
print("Mediana:", mediana)
print("Máximo:", max)
print("Mínimo:", min)
print("Desviación estándar:", desviacion_est)
print("Desviación estándar muestra:", desviacion_est_m)
print("Percentil 25:", percentil25)
print("Percentil 50:", percentil50)
print("Percentil 75:", percentil75)

Arreglo: [ 68  85   6  91   9  84  64  49  86  61  50  75  28  14  10  62  16  94
  99  60  19  15  94  57  10  52  69  54  54  72  60  43  27  67  10  82
  16  93  92  64  87  32  21  46  22  73  93  29  96  48  11  65   8  46
   3  39  72  96  37  90  61  92  69  38  67  83  39  55  87  40  47   7
  96  33  74  99   8  10  99  43  20  60  49  10  17  79  56  56  21  99
  88  99  25   7  29   6  67  20 100  76]
Media: 53.06
Mediana: 55.5
Máximo: 100
Mínimo: 3
Desviación estándar: 30.244278797815628
Desviación estándar muestra: 30.39664388704713
Percentil 25: 24.25
Percentil 50: 55.5
Percentil 75: 79.75


### 9. Concatenación y apilamiento

#### Crea dos arreglos de 1x5 y 5x1

In [40]:
B = np.array(np.random.randint(0,10,5))
B = B.reshape((1,5))
print(B)

[[8 7 9 7 3]]


In [41]:
C = np.array(np.random.randint(0,10,5))
C = C.reshape((5,1))
print(C)

[[8]
 [0]
 [7]
 [3]
 [0]]


#### Concátenalos en una sola fila y una sola columna

In [42]:
np.hstack((B,C.T))

array([[8, 7, 9, 7, 3, 8, 0, 7, 3, 0]])

In [43]:
np.vstack((B.T,C))

array([[8],
       [7],
       [9],
       [7],
       [3],
       [8],
       [0],
       [7],
       [3],
       [0]])

#### Aplica ambos arreglos con una matriz de 5x2

In [44]:
np.concatenate((B.T, C), axis=1)

array([[8, 8],
       [7, 0],
       [9, 7],
       [7, 3],
       [3, 0]])

### 10. Manipulación de datos en matrices grandes

#### Crea una matriz aleatoria de 100x100 con valores entre 0 y 1

In [45]:
m=np.random.rand(100,100)
m.shape

(100, 100)

#### Calcula la suma de todos los elementos de la matriz

In [46]:
np.sum(m)

4961.895883027826

#### Encuentra el valor máximo de cada fila y almacénalo en un nuevo arreglo.

In [47]:
maximo = np.max(m, axis=1)

In [48]:
print(f"Arreglo de máximos por fila (primeros 5 elementos): {maximo[:5]}")
print(f"Tamaño del nuevo arreglo: {maximo.shape}\n")

Arreglo de máximos por fila (primeros 5 elementos): [0.99711866 0.98266621 0.99452843 0.9901163  0.99710326]
Tamaño del nuevo arreglo: (100,)



### 11. Ordenamiento y selección

#### Genera un arreglo de 10 números aleatorios entre 0 y 50.

In [49]:
arreglo = np.random.randint(0, 51, size=10)
arreglo

array([ 9, 24, 32, 12, 21,  5, 32, 33, 15, 37])

#### Ordena el arreglo en orden ascendente y descendente

In [50]:
ascendente = np.sort(arreglo)
ascendente

array([ 5,  9, 12, 15, 21, 24, 32, 32, 33, 37])

In [51]:
descendente = np.sort(arreglo)[::-1]
descendente

array([37, 33, 32, 32, 24, 21, 15, 12,  9,  5])

#### Selecciona los 3 valores más altos y los 3 valores más bajos del arreglo ordenado

In [52]:
top3 = descendente[:3]
top3

array([37, 33, 32])

In [53]:
down3 = ascendente[:3]
down3

array([ 5,  9, 12])